declare @test table
(
  decimal_value int,
  roman_value varchar(max)
)

insert into @test values (1,'I')
insert into @test values (2,'II')
insert into @test values (3,'III')
insert into @test values (4,'IV')
insert into @test values (5,'V')
insert into @test values (6,'VI')
insert into @test values (7,'VII')
insert into @test values (8,'VIII')
insert into @test values (9,'IX')
insert into @test values (10,'X')
insert into @test values (11,'XI')
insert into @test values (12,'XII')
insert into @test values (13,'XIII')
insert into @test values (14,'XIV')
insert into @test values (15,'XV')
insert into @test values (16,'XVI')
insert into @test values (17,'XVII')
insert into @test values (18,'XVIII')
insert into @test values (19,'XIX')
insert into @test values (20,'XX')
insert into @test values (21,'XXI')
insert into @test values (22,'XXII')
insert into @test values (23,'XXIII')
insert into @test values (24,'XXIV')
insert into @test values (25,'XXV')
insert into @test values (26,'XXVI')
insert into @test values (27,'XXVII')
insert into @test values (28,'XXVIII')
insert into @test values (29,'XXIX')
insert into @test values (30,'XXX')
insert into @test values (31,'XXXI')
insert into @test values (32,'XXXII')
insert into @test values (33,'XXXIII')
insert into @test values (34,'XXXIV')
insert into @test values (35,'XXXV')
insert into @test values (36,'XXXVI')
insert into @test values (37,'XXXVII')
insert into @test values (39,'XXXIX')
insert into @test values (38,'XXXVIII')
insert into @test values (40,'XL')
insert into @test values (41,'XLI')
insert into @test values (29,'XXIX')
insert into @test values (43,'XLIII')
insert into @test values (44,'XLIV')
insert into @test values (45,'XLV')
insert into @test values (46,'XLVI')
insert into @test values (47,'XLVII')
insert into @test values (48,'XLVIII')
insert into @test values (49,'XLIX')
insert into @test values (50,'L')
insert into @test values (51,'LI')
insert into @test values (52,'LII')
insert into @test values (53,'LIII')
insert into @test values (54,'LIV')
insert into @test values (55,'LV')
insert into @test values (56,'LVI')
insert into @test values (57,'LVII')
insert into @test values (58,'LVIII')
insert into @test values (59,'LIX')
insert into @test values (60,'LX')
insert into @test values (61,'LXI')
insert into @test values (62,'LXII')
insert into @test values (63,'LXIII')
insert into @test values (64,'LXIV')
insert into @test values (65,'LXV')
insert into @test values (66,'LXVI')
insert into @test values (67,'LXVII')
insert into @test values (68,'LXVIII')
insert into @test values (69,'LXIX')
insert into @test values (70,'LXX')
insert into @test values (71,'LXXI')
insert into @test values (72,'LXXII')
insert into @test values (73,'LXXIII')
insert into @test values (74,'LXXIV')
insert into @test values (75,'LXXV')
insert into @test values (76,'LXXVI')
insert into @test values (77,'LXXVII')
insert into @test values (78,'LXXVIII')
insert into @test values (79,'LXXIX')
insert into @test values (80,'LXXX')
insert into @test values (81,'LXXXI')
insert into @test values (82,'LXXXII')
insert into @test values (83,'LXXXIII')
insert into @test values (84,'LXXXIV')
insert into @test values (85,'LXXXV')
insert into @test values (86,'LXXXVI')
insert into @test values (87,'LXXXVII')
insert into @test values (88,'LXXXVIII')
insert into @test values (89,'LXXXIX')
insert into @test values (90,'XC')
insert into @test values (91,'XCI')
insert into @test values (92,'XCII')
insert into @test values (93,'XCIII')
insert into @test values (94,'XCIV')
insert into @test values (95,'XCV')
insert into @test values (96,'XCVI')
insert into @test values (97,'XCVII')
insert into @test values (98,'XCVIII')
insert into @test values (99,'XCIX')
insert into @test values (100,'C')
insert into @test values (200,'CC')
insert into @test values (300,'CCC')
insert into @test values (400,'CD')
insert into @test values (500,'D')
insert into @test values (600,'DC')
insert into @test values (700,'DCC')
insert into @test values (800,'DCCC')
insert into @test values (900,'CM')
insert into @test values (1000,'M')
insert into @test values (0,'Error: input must be greater than 0')
insert into @test values (-1,'Error: input must be greater than 0')


declare @num_errors int

select @num_errors = count(1)
  from @test t
 where t.roman_value <> dbo.decimal_to_roman(t.decimal_value)

if @num_errors <> 0
  print 'Fail'
else
  print 'Pass'
