(DEFUN CHECK-NCADR? (L)
	(COND ((NULL (CDR L)) T)
		((CHAR-EQUAL (CAR L) (CAR (CDR L))) NIL)
		(T (CHECK-NCADR? (CDR L)))))

(DEFUN CHECK-STR? (STR)
	(CHECK-NCADR? (LOOP FOR C ACROSS (SORT (STRING-DOWNCASE STR) #'CHAR-LESSP) COLLECT C)))

(DEFUN MAX-CAR (A B)
	(COND ((> (CAR A) (CAR B)) A) (T B)))

(DEFUN FIND-MAX? (LSTR)
	(COND ((NULL LSTR) (CONS 0 '""))
		(T (MAX-CAR
			(COND
				((CHECK-STR? (CAR LSTR)) (CONS (LENGTH (CAR LSTR)) (CAR LSTR)))
				(T (CONS 0 '"")))
			(FIND-MAX? (CDR LSTR))))))

(DEFUN SPLIT-BY-ONE-SPACE (STRING)
	(LOOP FOR I = 0 THEN (1+ J) AS J = (POSITION #\SPACE STRING :START I)
		COLLECT (SUBSEQ STRING I J) WHILE J))

(DEFUN MAIN (FILE)
	(WITH-OPEN-FILE (STREAM FILE)
		(PROG (M)
			(SETQ M (CONS 0 '""))
			(LOOP FOR LINE = (READ-LINE STREAM NIL) WHILE LINE DO
				(SETQ M (MAX-CAR M (FIND-MAX? (SPLIT-BY-ONE-SPACE LINE)))))
			(RETURN M))))

